### ISSUE TITLE
Crash issue in Exercise 2: Parsing the JSON Response

### ISSUE THREAD

**Issue by TheCodingArcher** [udacity/andfun-kotlin-mars-real-estate#10]
**Exercise 2: Parsing the JSON Response with Moshi**.

I did exactly what has been taught by @DAGalpin in the tutorial but keep getting crash again & again.
Logcat says,
```
2020-09-05 20:00:48.716 28468-28468/a.b.c E/AndroidRuntime: FATAL EXCEPTION: main
    Process: a.b.c, PID: 28468
    java.lang.IllegalArgumentException: Unable to create converter for java.util.List<a.b.c.marsrealestate.network.MarsProperty>
        for method MarsApiService.getProperties
        at retrofit2.Utils.methodError(Utils.java:54)
        at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:126)
        at retrofit2.HttpServiceMethod.parseAnnotations(HttpServiceMethod.java:85)
        at retrofit2.ServiceMethod.parseAnnotations(ServiceMethod.java:39)
        at retrofit2.Retrofit.loadServiceMethod(Retrofit.java:202)
        at retrofit2.Retrofit$1.invoke(Retrofit.java:160)
        at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
        at $Proxy2.getProperties(Unknown Source)
        at a.b.c.marsrealestate.overview.OverviewViewModel.getMarsRealEstateProperties(OverviewViewModel.kt:28)
        at a.b.c.marsrealestate.overview.OverviewViewModel.<init>(OverviewViewModel.kt:22)
        at java.lang.Class.newInstance(Native Method)
        at androidx.lifecycle.ViewModelProvider$NewInstanceFactory.create(ViewModelProvider.java:219)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:187)
        at androidx.lifecycle.ViewModelProvider.get(ViewModelProvider.java:150)
        at a.b.c.marsrealestate.overview.OverviewFragment$viewModel$2.invoke(OverviewFragment.kt:17)
        at a.b.c.marsrealestate.overview.OverviewFragment$viewModel$2.invoke(OverviewFragment.kt:11)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at a.b.c.marsrealestate.overview.OverviewFragment.getViewModel(Unknown Source:7)
        at a.b.c.marsrealestate.overview.OverviewFragment.onCreateView(OverviewFragment.kt:32)
        at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
        at androidx.fragment.app.FragmentManagerImpl.addAddedFragments(FragmentManagerImpl.java:2100)
        at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1874)
        at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1830)
        at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
        at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
        at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
        at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2659)
        at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
        at androidx.fragment.app.FragmentController.dispatchActivityCreated(FragmentController.java:246)
        at androidx.fragment.app.FragmentActivity.onStart(FragmentActivity.java:542)
        at androidx.appcompat.app.AppCompatActivity.onStart(AppCompatActivity.java:210)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1425)
        at android.app.Activity.performStart(Activity.java:7825)
        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3294)
        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
2020-09-05 20:00:48.717 28468-28468/a.b.c E/AndroidRuntime:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2016)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.IllegalArgumentException: Platform class a.b.c.marsrealestate.network.MarsProperty requires explicit JsonAdapter to be registered
    for class a.b.c.marsrealestate.network.MarsProperty
    for java.util.List<a.b.c.marsrealestate.network.MarsProperty>
        at com.squareup.moshi.Moshi$LookupChain.exceptionWithLookupStack(Moshi.java:349)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:150)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:68)
        at com.squareup.moshi.CollectionJsonAdapter.newArrayListAdapter(CollectionJsonAdapter.java:52)
        at com.squareup.moshi.CollectionJsonAdapter$1.create(CollectionJsonAdapter.java:36)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:98)
        at retrofit2.converter.moshi.MoshiConverterFactory.responseBodyConverter(MoshiConverterFactory.java:89)
        at retrofit2.Retrofit.nextResponseBodyConverter(Retrofit.java:362)
        at retrofit2.Retrofit.responseBodyConverter(Retrofit.java:345)
        at retrofit2.HttpServiceMethod.createResponseConverter(HttpServiceMethod.java:124)
        	... 48 more
     Caused by: java.lang.IllegalArgumentException: Platform class a.b.c.marsrealestate.network.MarsProperty requires explicit JsonAdapter to be registered
        at com.squareup.moshi.ClassJsonAdapter$1.create(ClassJsonAdapter.java:65)
        at com.squareup.moshi.Moshi.adapter(Moshi.java:138)
```

**Comment by TheCodingArcher** [comment]
Okay, so firstly, I think its a big error of **MoshiConverterFactory** which is not supporting (haven't gone into deep though).
So to fix the crash, always use GsonConverterFactory.

In build.gradle (app), add:
`implementation "com.squareup.retrofit2:converter-gson:$version_retrofit"`
remove:
```
implementation "com.squareup.moshi:moshi-kotlin:$version_moshi"
implementation "com.squareup.retrofit2:converter-moshi:$version_retrofit"
```

In proguard-rules.pro, add:
```
-keepclassmembers class com.squareup.moshi.FromJson** { *; }
-keepclassmembers class com.squareup.moshi.ToJson** { *; }
```

In MarsApiService.kt, replace `MoshiConverterFactory.create(moshi)` with `GsonConverterFactory.create()`

Rest, everything should work as shown. Cheers !!
