### ISSUE TITLE
Solution code for exercise 1 throwing `INTERNAL_ERROR`

### ISSUE THREAD

**Issue by Mordred** [udacity/andfun-kotlin-mars-real-estate#21]
Hi, I'm trying solution 1 but I'm always getting this error:

```
2022-02-24 19:48:43.848 7223-7223/com.example.android.marsrealestate E/OverviewViewModel: stream was reset: INTERNAL_ERROR
    okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:384)
        at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:286)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okio.RealBufferedSource.exhausted(RealBufferedSource.java:61)
        at okio.InflaterSource.refill(InflaterSource.java:102)
        at okio.InflaterSource.read(InflaterSource.java:62)
        at okio.GzipSource.read(GzipSource.java:80)
        at okio.RealBufferedSource.read(RealBufferedSource.java:51)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
        at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314)
        at okio.Buffer.writeAll(Buffer.java:1143)
        at okio.RealBufferedSource.readString(RealBufferedSource.java:203)
        at okhttp3.ResponseBody.string(ResponseBody.java:182)
        at retrofit2.converter.scalars.ScalarResponseBodyConverters$StringResponseBodyConverter.convert(ScalarResponseBodyConverters.java:30)
        at retrofit2.converter.scalars.ScalarResponseBodyConverters$StringResponseBodyConverter.convert(ScalarResponseBodyConverters.java:25)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
        at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
```

![image](https://user-images.githubusercontent.com/29232/155588312-8ed021da-c08e-49e0-9891-a7022d096895.png)

**Comment by Suparna-here** [comment]
I am receiving this error code.
Unable to progress.

**Comment by Suparna-here** [comment]
Unable to run any solution code because of server error.

**Comment by Jenovas** [comment]
Have the same error, probably the only way to move forward is to fake the response from the server.
Open in your web browser - https://mars.udacity.com/realestate?filter=all, copy / paste the whole thing into your project and locally do everything instead of doing in online.

**Comment by SudKul** [comment]
That was a temporary issue from Udacity. 
The https://mars.udacity.com/realestate?filter=all was down for a while back then.
